# Generated by Django 2.1.7 on 2019-04-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='video',
            name='passwd',
        ),
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
    ]
